spring:
    datasource:
        url: jdbc:mysql://db-java-study-02.cyw9uluxdxar.ap-northeast-1.rds.amazonaws.com:3306/favoritefruits
        username: admin
        password: ppppaaa
        driver-class-name: com.mysql.cj.jdbc.Driver
    sql:
        init:
            mode: always
server:
    port: 38080