spring:
    datasource:
        url: jdbc:mysql://localhost:3306/favoritefruits
        username: root
        password: root
        driver-class-name: com.mysql.cj.jdbc.Driver
    sql:
        init:
            mode: always
server:
    port: 38080