spring:
    datasource:
        url: db-java-study-02.cyw9uluxdxar.ap-northeast-1.rds.amazonaws.com/favoritefruits
        username: admin
        password: ppppaaaa
        driver-class-name: com.mysql.cj.jdbc.Driver
    sql:
        init:
            mode: always
server:
    port: 38080
